### ISSUE TITLE
how to use .env-production and .env-development

### ISSUE THREAD

**Issue by cannycookie** [rennokki/laravel-aws-eb#18]
This is brilliant and has solved many issues for us, thank you. 

Now only stuck with how to use different .env files for master and development instances?

Maybe have different buckets for each environment?  Which then requires using a variable in the script to know which env we are in?

Any advice gratefully received. :-)

**Comment by cannycookie** [comment]
Found a solution to get the environment name in the config file.  

Now just have to upload .env files with the environment name suffix :-)

```
files:
  "/tmp/.env":
    mode: "000777"
    owner: root
    group: root
    authentication: "S3Auth"
    source: "https://elasticbeanstalk-eu-west-1-670082197053.s3-eu-west-1.amazonaws.com/.env-`{"Ref": "AWSEBEnvironmentName" }`"
```
